### ISSUE TITLE
似乎登录不了了，一直在转圈圈

### ISSUE THREAD

**Issue by paulyu666** [Erope/BaiduPCS-Go#1]
我原来使用旧版，无法使用账号密码登录，但是可以使用BDUSS登录，现在换了这个版本，登录一直在转圈圈

**Comment by Erope** [comment]
@paulyu666 好的 晚上我看看 如果不介意的话可以Tg私聊我提供下账户密码吗?

**Comment by Erope** [comment]
已经修复

**Comment by paulyu666** [comment]
大佬能帮忙打包下吗？不是开发，没有Google到

**Comment by Erope** [comment]
@paulyu666 抱歉 现在不提供打包了 安装好Go环境就可以自己编译了

**Comment by paulyu666** [comment]
@Erope 大佬不好意思，努力编译好了，放在什么地方呢能指点下吗，我编译好的本地可运行，不知道放在路由器下的哪个文件夹下。
编译好的文件也可以在我本地运行，我找了所有包含baidu的文件，没有一个和我这个编译好的名字一样
我在/usr/bin下找到了一个baidupcs-web的文件，替换后不能运行
请大佬指点下，谢谢

![image](https://user-images.githubusercontent.com/64824531/149725073-15eb963d-4189-4c22-9e6b-2a304d31a4e4.png)

**Comment by Erope** [comment]
@paulyu666 OpenWRT的插件并非我编写，请询问插件编写者。
